@echo off
echo Cleaning node_modules directory...
rmdir /s /q node_modules
echo Deleting package-lock.json...
del package-lock.json
echo Fixing package.json...
node fix-package.js
echo Running fresh npm install...
npm install
echo Done! You can now run 'npm run build'
